<div class="<?=$this->cssClass?>">
    <? if ($this->row->disclaimer_type == 'de' && $this->row->disclaimer_name) { ?>
        <span class="imprintHeadline"><?=trlVps('Disclaimer');?></span>
        <div class="vpsSwitchDisplay">
            <p><a href="#" class="switchLink">1. Inhalt des Onlineangebotes</a></p>
            <div class="switchContent"><?=$this->row->disclaimer_name;?> übernimmt keinerlei Gewähr für die Aktualität, Korrektheit, Vollständigkeit oder Qualität der bereitgestellten Informationen. Haftungsansprüche gegen <?=$this->row->disclaimer_name;?>, welche sich auf Schäden materieller oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und unvollständiger Informationen verursacht wurden, sind grundsätzlich ausgeschlossen, sofern seitens <?=$this->row->disclaimer_name;?> kein nachweislich vorsätzliches oder grob fahrlässiges Verschulden vorliegt. Alle Angebote sind freibleibend und unverbindlich. <?=$this->row->disclaimer_name;?> behält es sich ausdrücklich vor, Teile der Seiten oder das gesamte Angebot ohne gesonderte Ankündigung zu verändern, zu ergänzen, zu löschen oder die Veröffentlichung zeitweise oder endgültig einzustellen.</div>
        </div>
        <div class="vpsSwitchDisplay">
            <p><a href="#" class="switchLink">2. Verweise und Links</a></p>
            <div class="switchContent">Bei direkten oder indirekten Verweisen auf fremde Webseiten ("Hyperlinks"), die außerhalb des Verantwortungsbereiches von <?=$this->row->disclaimer_name;?> liegen, würde eine Haftungsverpflichtung ausschließlich in dem Fall in Kraft treten, in dem <?=$this->row->disclaimer_name;?> von den Inhalten Kenntnis hat und es ihm technisch möglich und zumutbar wäre, die Nutzung im Falle rechtswidriger Inhalte zu verhindern. <?=$this->row->disclaimer_name;?> erklärt hiermit ausdrücklich, dass zum Zeitpunkt der Linksetzung keine illegalen Inhalte auf den zu verlinkenden Seiten erkennbar waren. Auf die aktuelle und zukünftige Gestaltung, die Inhalte oder die Urheberschaft der verlinkten/verknüpften Seiten hat <?=$this->row->disclaimer_name;?> keinerlei Einfluss. Deshalb distanziert <?=$this->row->disclaimer_name;?> sich hiermit ausdrücklich von allen Inhalten aller verlinkten /verknüpften Seiten, die nach der Linksetzung verändert wurden. Diese Feststellung gilt für alle innerhalb des eigenen Internetangebotes gesetzten Links und Verweise sowie für Fremdeinträge in von <?=$this->row->disclaimer_name;?> eingerichteten Gästebüchern, Diskussionsforen, Linkverzeichnissen, Mailinglisten und in allen anderen Formen von Datenbanken, auf deren Inhalt externe Schreibzugriffe möglich sind. Für illegale, fehlerhafte oder unvollständige Inhalte und insbesondere für Schäden, die aus der Nutzung oder Nichtnutzung solcherart dargebotener Informationen entstehen, haftet allein der Anbieter der Seite, auf welche verwiesen wurde, nicht derjenige, der über Links auf die jeweilige Veröffentlichung lediglich verweist.</div>
        </div>
        <div class="vpsSwitchDisplay">
            <p><a href="#" class="switchLink">3. Urheber- und Kennzeichenrecht</a></p>
            <div class="switchContent"><?=$this->row->disclaimer_name;?> ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Grafiken, Tondokumente, Videosequenzen und Texte zu beachten, von <?=$this->row->disclaimer_name;?> selbst erstellte Grafiken, Tondokumente, Videosequenzen und Texte zu nutzen oder auf lizenzfreie Grafiken, Tondokumente, Videosequenzen und Texte zurückzugreifen. Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte geschützten Marken- und Warenzeichen unterliegen uneingeschränkt den Bestimmungen des jeweils gültigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigentümer. Allein aufgrund der bloßen Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte Dritter geschützt sind! Das Copyright für veröffentlichte, von <?=$this->row->disclaimer_name;?> selbst erstellte Objekte bleibt allein beim Autor der Seiten. Eine Vervielfältigung oder Verwendung solcher Grafiken, Tondokumente, Videosequenzen und Texte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdrückliche Zustimmung von <?=$this->row->disclaimer_name;?> nicht gestattet.</div>
        </div>
        <div class="vpsSwitchDisplay">
            <p><a href="#" class="switchLink">4. Datenschutz</a></p>
            <div class="switchContent">Sofern innerhalb des Internetangebotes die Möglichkeit zur Eingabe persönlicher oder geschäftlicher Daten (Emailadressen, Namen, Anschriften) besteht, so erfolgt die Preisgabe dieser Daten seitens des Nutzers auf ausdrücklich freiwilliger Basis. Die Inanspruchnahme und Bezahlung aller angebotenen Dienste ist - soweit technisch möglich und zumutbar - auch ohne Angabe solcher Daten bzw. unter Angabe anonymisierter Daten oder eines Pseudonyms gestattet. Die Nutzung der im Rahmen des Impressums oder vergleichbarer Angaben veröffentlichten Kontaktdaten wie Postanschriften, Telefon- und Faxnummern sowie E-Mailadressen durch Dritte zur Übersendung von nicht ausdrücklich angeforderten Informationen ist nicht gestattet. Rechtliche Schritte gegen die Versender von so genannten Spam-Mails bei Verstößen gegen dieses Verbot sind ausdrücklich vorbehalten.</div>
        </div>
        <div class="vpsSwitchDisplay">
            <p><a href="#" class="switchLink">5. Rechtswirksamkeit dieses Haftungsausschlusses</a></p>
            <div class="switchContent">Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten, von dem aus auf diese Seite verwiesen wurde. Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollständig entsprechen sollten, bleiben die übrigen Teile des Dokumentes in ihrem Inhalt und ihrer Gültigkeit davon unberührt.
            Der vorliegende Haftungsauschlusstext basiert auf dem kostenlosen Dienst von
            <a href="http://www.disclaimer.de/" rel="popup_blank">www.disclaimer.de</a></div>
        </div>
    <? } ?>
</div>

