<?php
class Kwc_Box_TitleEditable_Form extends Kwc_Abstract_Form
{
    protected function _initFields()
    {
        parent::_initFields();
        $this->add(new Kwf_Form_Field_TextField('title', trlKwf('Page Title')))
            ->setWidth(400)
            ->setHelpText(trlKwf('optional, if not set the title will be autogenerated from the sitename.'));
    }
}
    
