<?php
class Kwc_Advanced_Imprint_GoogleAnalytics_Component extends Kwc_Abstract
{
    public static function getSettings()
    {
        $ret = array_merge(parent::getSettings(), array(
            'componentName' => trlKwfStatic('Imprint').'.Google-Analytics',
            'cssClass' => 'webStandard'
        ));
        $ret['componentCategory'] = 'admin';
        return $ret;
    }

    public function getTemplateVars()
    {
        $ret = parent::getTemplateVars();
        $content = array(
            'en' => 'This website uses Google Analytics, a web analytics service provided by
                    Google, Inc. (“Google”). Google Analytics uses “cookies”, which are
                    text files placed on your computer, to help the website analyze how
                    users use the site. The information generated by the cookie about your
                    use of the website (including your IP address) will be transmitted to
                    and stored by Google on servers in the United States. In case of
                    activation of the IP anonymization, Google will truncate/anonymize the
                    last octet of the IP address for Member States of the European Union as
                    well as for other parties to the Agreement on the European Economic
                    Area. Only in exceptional cases, the full IP address is sent to and
                    shortened by Google servers in the USA. On behalf of the website
                    provider Google will use this information for the purpose of evaluating
                    your use of the website, compiling reports on website activity for
                    website operators and providing other services relating to website
                    activity and internet usage to the website provider. Google will not
                    associate your IP address with any other data held by Google. You may
                    refuse the use of cookies by selecting the appropriate settings on your
                    browser. However, please note that if you do this, you may not be able
                    to use the full functionality of this website. Furthermore you can
                    prevent Google’s collection and use of data (cookies and IP address) by
                    downloading and installing the browser plug-in available under
                     <a href="https://tools.google.com/dlpage/gaoptout?hl=en-GB">https://tools.google.com/dlpage/gaoptout?hl=en-GB</a>.',
            'de' => 'Diese Website verwendet Google Analytics, einen Webanalysedienst von Google Inc.
                    Google Analytics verwendet "Cookies", Textdateien, die auf Ihrem Computer
                    gespeichert werden und die eine Analyse der Nutzung dieser Website ermöglicht.
                    Diese Informationen betr. Nutzung dieser Website wird an einen Server der
                    Google in den USA übertragen und dort gespeichert. Google verwendet diese
                    Informationen, um Ihre Nutzung der Website auszuwerten. Google überträgt
                    diese Informationen gegebenenfalls an Dritte, sofern dies gesetzlich vorgeschrieben
                    oder soweit Dritte diese Daten im Auftrag von Google verarbeiten. Google
                    wird in keinem Fall Ihre IP-Adresse (Ihren individuellen Internet Zugang)
                    mit anderen Daten von Google in Verbindung bringen. Sie können die
                    Installation der Cookies durch eine entsprechende Einstellung Ihrer Browser
                    Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem
                    Fall gegebenenfalls nicht sämtliche Funktionen dieser Website voll
                    umfänglich nutzen können. Durch die Nutzung dieser Website erklären Sie
                    sich mit der Bearbeitung der über Sie erhobenen Daten durch Google in der
                    zuvor beschriebenen Art und Weise und zu dem zuvor benannten Zweck
                    einverstanden. Der Datenerhebung und -speicherung kann jederzeit mit Wirkung
                    für die Zukunft <a href="https://tools.google.com/dlpage/gaoptout?hl=de" rel="popup_blank">widersprochen</a>
                    werden. Diese Website verwendet Google Analytics mit der Erweiterung
                    „_anonymizeIp()“, dadurch werden IP-Adressen nur gekürzt weiterverarbeitet,
                    um eine direkte Personenbeziehbarkeit auszuschließen.'
        );
        $l = $this->getData()->getLanguage();
        if (isset($content[$l])) {
            $ret['content'] = $content[$l];
        } else {
            $ret['content'] = $content['en'];
        }
        return $ret;
    }
}
